const config = Object.freeze({
  TILE_DISTRIBUTION:
    'AAAAAAAAABBCCDDDDDEEEEEEEEEEEEEFFGGGHHHHIIIIIIIIJKLLLLMMNNNNNOOOOOOOOPPQRRRRRRSSSSSTTTTTTTUUUUVVWWXYYZ',
  NUM_LETTERS: 6,
});

export default config;
